name: real-estate-analytics
channels:
  - conda-forge
  - defaults
dependencies:
  # Python
  - python=3.9
  
  # Java for Spark
  - openjdk=11
  
  # Core Data Science Stack
  - pandas>=2.0.0
  - numpy>=1.22.0
  - scipy>=1.13.0
  - scikit-learn>=1.3.0
  
  # Visualization
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  - plotly>=5.15.0
  
  # Jupyter
  - jupyter>=1.0.0
  - jupyterlab>=4.0.0
  - ipykernel>=6.0.0
  
  # Development Tools
  - black>=23.0.0
  - flake8>=6.0.0
  - isort>=5.0.0
  - pytest>=7.0.0
  - pytest-cov>=4.0.0
  
  # File Processing
  - openpyxl>=3.1.0
  - xlrd>=2.0.0
  
  # Configuration
  - pyyaml>=6.0
  
  # Performance
  - pyarrow>=12.0.0
  
  # Utilities
  - tqdm>=4.65.0
  - python-dotenv>=1.0.0
  
  # Pip dependencies (not available in conda)
  - pip
  - pip:
    - pyspark==3.5.5
    - findspark==2.0.1
    - fastparquet>=2023.4.0
    - sphinx>=7.0.0
    - sphinx-rtd-theme>=1.3.0